### ISSUE TITLE
Smooth lighting broken in rev1927

### ISSUE THREAD

**Issue by HiPhish** [nuvie/nuvie#46]
I just downloaded the latest build (rev1927) and smooth lighting is broken: the closer I get to a light source, the darker everything gets. Standing at medium distance from the light source produces the most light.

Original lighting and no lighting work as they should.

**Comment by yuv422** [comment]
strange it is working for me. Are you running on windows? Does it happen for new style as well as in original mode?

**Comment by yuv422** [comment]
Also are you running 16 or 32bpp video?

**Comment by HiPhish** [comment]
I'm running on OS X 10.11.2 and it happens in all styles. I have made a few comparison screenshots:
![screen shot 2015-12-27 at 14 33 29](https://cloud.githubusercontent.com/assets/4954650/12010463/485a69bc-aca8-11e5-80d4-36f10215792b.png)

Note that there is *some* lighting, but it's not the right amount. It can get even darker when I leave the shrine. Also notice how in the second set the lighting seems to be inverted.

How do I find out whether I'm in 16 or 32 bpp video?

**Comment by DominusExult** [comment]
I can't reproduce this. Have you tried nuking (but saving) your preference file, just in case that some weird combination of settings that causes this?

**Comment by DominusExult** [comment]
bah, *NOW* after *I* nuked my preference file, I can confirm the issue...

**Comment by DominusExult** [comment]
yuv422, the issue happens with the point scaler. Something went wrong when you switched to SDL2 point scaling in 6cc1d34.
Easily tested by setting scaler to point and using the snapshot from our download page. When you force the app to run in 32bit mode everything works fine (since the 32bit arch is using SDL 1.x), but in 64bit mode it behaves like HiPhish describes.

**Comment by yuv422** [comment]
Cool, I'll take a look :)

**Comment by yuv422** [comment]
@HiPhish Could you confirm that this is working for you now. It should be fixed in the latest daily snapshot.

**Comment by DominusExult** [comment]
works for me now

**Comment by HiPhish** [comment]
Works great now, closing issue.
