### ISSUE TITLE
Close settings gump without keyboard

### ISSUE THREAD

**Issue by DominusExult** [nuvie/nuvie#48]
Currently you can only close the settings gump by hitting ESC. I think it might be nice if there were another way, for example by clicking outside of the gump (or maybe by a double-click outside)

**Comment by Zabeus** [comment]
I agree this is annoying.
Now we just need a way to open the settings gump without the keyboard.

**Comment by osem** [comment]
Looks like something went wrong adding this button...

Line 93: button_index[last_index += 1] = cheats_button;

It just adds the cheats button a second time!
