### ISSUE TITLE
Nuvie on SDL2: frozen keyboard after exit

### ISSUE THREAD

**Issue by vanfanel** [nuvie/nuvie#61]
Hi there,

On some systems (like the Pi, where SDL2 apps run x-less luckily!), pressing Q on the main menu causes the TTY console keyboard to be frozen and hence unusable.
I have been debugging this and it seems SDL_Quit() is never called when Q is pressed on the main tittle screen: main returns 1 at line 80, and that's it. SDL2 is not properly deinitialized and that causes the keybard to be frozen on exit.

**Comment by yuv422** [comment]
I've pushed a change to master that should call SDL_Quit() when exiting the application from the main title screen. Could you test this to see if it fixes your problem?

1107c44844899f73fae24e022adb81b8ead93c01

**Comment by vanfanel** [comment]
@yuv422 : Yes, it now works as expected and console keyboard isn't frozen anymore. Thanks! :)
