### ISSUE TITLE
Question about the object and their location

### ISSUE THREAD

**Issue by pantinor** [nuvie/nuvie#76]
Not an issue but a question you may be able to help me with.
I am writing a script to parse the original 64 SAVEGAME OBJBLK files to load up the objects and put them on top off a world tiledmap layer 1024x1024.  But I got stuck translating the X,Y,Z bytes to the world X,Y coordinates.  Can you help any pointers on what I may be missing to do that translation?
Here below is some code snippet shows where I am in reading the block bytes and taking the x,y,z, and missed the way to translate that to the world.  Thanks.

`
short count = dis.readShort();
for (int i = 0; i < count; i++) {
byte status = dis.readByte();
byte h = dis.readByte();
byte d1 = dis.readByte();
byte d2 = dis.readByte();
short type = dis.readShort();
byte quantity = dis.readByte();
byte quality = dis.readByte();

int x = ((d1 & 0x3) << 8 | h) & 0xff;
int y = ((d2 & 0xf) << 6 | (d1 >> 2)) & 0xff;
int z = (d2 >> 4) & 0xff;

`

**Comment by yuv422** [comment]
Here's the logic from Nuvie.
` obj->x = buf->read1(); // h
 b1 = buf->read1();
 obj->x += (b1 & 0x3) << 8;

 obj->y = (b1 & 0xfc) >> 2;
 b2 = buf->read1();
 obj->y += (b2 & 0xf) << 6;

obj->z = (b2 & 0xf0) >> 4;`

Don't forget that the values are larger than 255 so ANDing with 0xff is going to cause you problems. ;)

**Comment by pantinor** [comment]
Thanks I am all set with this issue now, your pointer was helpful.  I am using java here and also needed to use a little endian input stream reading unsigned byte as well.  I added the script in my repository under "u6-java" as well.

**Comment by yuv422** [comment]
Great. Just to let you know. Nuvie can export the map as a TMX file. :) Just press Alt-913 in game.

http://ultimacodex.com/2015/01/nuvie-export-maps-to-tiled-map-editors-tmx-format/
